author: Ujjwal Chafle
objc: true
umbrella_header: ZappMerchantLib/ZappMerchantLib.h
framework_root: .
sdk: iphonesimulator
copyright: IPCO 2012 Limited
github_url: https://github.com/vocalinkzapp/pbba-merchant-button-library-ios-R4
exclude:
 - ZappMerchantLib/PBBAAnimatable.h
 - ZappMerchantLib/PBBAUIElementAppearance.h
